defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost

development:
  database: code_dev
  <<: *defaults

test: &test
  database: code_test
  <<: *defaults
  
staging:
  database: code_staging
  <<: *defaults

production:
  database: code_dev
  <<: *defaults

cucumber:
  <<: *test
